name: Self-Hosted Server with Auto-Restart

on:
  workflow_dispatch:

jobs:
  run-server:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install GitHub CLI
        run: sudo apt-get update && sudo apt-get install -y gh

      # Restore previous state
      - name: Restore saved state
        uses: actions/cache@v4
        with:
          path: /var/lib/pterodactyl/volumes
          key: pterodactyl-volumes

      # Schedule workflow re-run before GitHub timeout
      - name: Schedule workflow re-run before timeout
        run: |
          (sleep $((5 * 3600 + 40 * 60)) && \
          echo "Triggering rerun..." && \
          gh workflow run $(basename "${GITHUB_WORKFLOW_REF%/*}")) &
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Write your config
      - name: Write server config
        run: |
          sudo mkdir -p /var/lib/pterodactyl/volumes
          sudo tee /var/lib/pterodactyl/volumes/config.yml > /dev/null <<'EOF'
          debug: false
          uuid: e53ecb53-e284-4d1d-ac98-237fca10bd8d
          token_id: WB9zGpp20CM94cwe
          token: Cx3VEJD2Mg1iKary0cljYxhBe4UEx9W7J1Udb8fWlBrbeCbCdVNUYjIWFtfS9ICP
          api:
            host: 0.0.0.0
            port: 8080
            ssl:
              enabled: false
              cert: /etc/letsencrypt/live/100.89.132.120/fullchain.pem
              key: /etc/letsencrypt/live/100.89.132.120/privkey.pem
            upload_limit: 100
          system:
            data: /var/lib/pterodactyl/volumes
            sftp:
              bind_port: 2022
          allowed_mounts: []
          remote: 'http://100.89.132.120'
          EOF

      # Start your server here — replace this with your actual start command
      - name: Start server
        run: |
          echo "Starting server..."
          # Example: If it's a binary named server
          chmod +x ./server || true
          ./server || echo "Replace './server' with your real start command"

      # Save state at the end
      - name: Save state for next run
        uses: actions/cache@v4
        with:
          path: /var/lib/pterodactyl/volumes
          key: pterodactyl-volumes
